language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

go_import_path: github.com/berryland/sugar
  
before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - $GOPATH/bin/dep ensure
  
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
